# -*- coding: utf-8 -*-
"""download_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hNMDdb4BJK6E4ahxVztApdCGBzYSDfTF
"""

from obspy import UTCDateTime
from obspy.clients.fdsn import Client
import numpy as np
import os
import matplotlib.pyplot as plt

def download_seismic_data():
  # Changed directory to /content for easy download
  os.makedirs("/content/data", exist_ok=True)

  #Initialize IRIS client
  client=Client("IRIS")

  #Define parameters
  #Using a moderate earthquake that produced clear signals

  #Time window around the earthquake
  starttime=UTCDateTime("2020-01-07T08:25:26")
  endtime=starttime+600 #10 minutes of data

  #Request parameters
  network="IU"
  station="SSPA"
  location="00"
  channel="BHZ"

  print(f"Network: {network}")
  print(f"Station: {station}")
  print(f"Channel: {channel}")
  print(f"Time: {starttime} to {endtime}")

  #Download waveform data
  try:
    st=client.get_waveforms(network, station, location, channel, starttime, endtime)
    print(f"Download {len(st)} trace(s)")
    print(f"Sampling rate: {st[0].stats.sampling_rate} Hz")
    print(f"Number of samples: {st[0].stats.npts}")
    print(f"Duration: {st[0].stats.endtime-st[0].stats.starttime:.1f} seconds")
  except Exception as e:
    print(f"Error downloadiing data: {e}")
    print("\nTrying alternative station...")
    station="ANMO"
    st=client.get_waveforms(network, station, location, channel, starttime, endtime)
    print(f"Download from {station}")

  #Detrend and filter
  st.detrend(type='linear')
  st.filter('bandpass', freqmin=0.01, freqmax=1.0, corners=4)
  print("Applied detrending and bandpass filter (0.01-1.0 Hz)")

  #Extract trace data
  trace=st[0]
  data=trace.data
  times=np.arange(len(data))/ trace.stats.sampling_rate

  #Format 1: Binary file (most efficient)
  # Changed directory to /content for easy download
  binary_file="/content/data/seismic_data.bin"
  with open(binary_file, "wb") as f:
    #Write header info
    np.array([len(data)], dtype=np.int32).tofile(f)
    np.array([trace.stats.sampling_rate], dtype=np.float32).tofile(f)

    #Write data
    data.astype(np.float32).tofile(f)
  print(f"Binary file: {binary_file}")

  #Format 2: CSV file (human readable, easy to debug)
  # Changed directory to /content for easy download
  csv_file="/content/data/seismic_data.csv"
  np.savetxt(csv_file, np.column_stack([times, data]),
             delimiter=',', header='time, amplitude', comments='')
  print(f"CSV file: {csv_file}")

  #Format 3: Metadata file
  # Changed directory to /content for easy download
  metadata_file="/content/data/metadata.txt"
  with open(metadata_file, 'w') as f:
    f.write(f"Network: {network}\n")
    f.write(f"Station: {station}\n")
    f.write(f"Channel: {channel}\n")
    f.write(f"Start Time: {trace.stats.starttime}\n")
    f.write(f"End Time: {trace.stats.endtime}\n")
    f.write(f"Sampling Rate: {trace.stats.sampling_rate}Hz\n")
    f.write(f"Number of Samples: {len(data)}\n")
    f.write(f"Duration: {trace.stats.endtime-trace.stats.starttime:.2f} seconds\n")
  print(f"Metadata file: {metadata_file}")

  #Create visualizetion
  fig, (ax1, ax2)=plt.subplots(2, 1, figsize=(12, 8))

  #Plot 1: Full waveform
  ax1.plot(times, data, 'b-', linewidth=0.5)
  ax1.set_xlabel("Time (seconds)")
  ax1.set_ylabel("Amplitude")
  ax1.set_title(f'Real Seismic Data: {network}.{station}.{channel}\n' f'{trace.stats.starttime}')
  ax1.grid(True, alpha=0.3)

  #Plot 2: zoomed in to show detail
  zoom_start=len(data)//3
  zoom_end=zoom_start+1000
  ax2.plot(times[zoom_start:zoom_end], data[zoom_start:zoom_end], 'r-', linewidth=1)
  ax2.set_xlabel('Time Amplitude')
  ax2.set_ylabel("Amplitude")
  ax2.set_title("Zoomed view (showing waveform detail)")
  ax2.grid(True, alpha=0.3)

  plt.tight_layout()
  # Changed directory to /content for easy download
  plt.savefig('/content/data/seismic_waveform.png', dpi=150)

  print("\nFiles Created:")
  print(f"1. {binary_file} (for C++ -efficient)")
  print(f"2. {csv_file} (for debugging)")
  print(f"3. {metadata_file} (information)")
  print(f"4. /content/data/seismic_waveform.png (visualization)")

  return trace

if __name__=="__main__":
  try:
    trace=download_seismic_data()
  except Exception as e:
    print(f"\nError: {e}")